import Package.TaxiCar;
import Package.Tiger;
import Package.FullTimeEmployee;
import Package.PartTimeEmployee;
import Package.OfflineStudent;
import Package.OnlineStudent;
import Package.Customer;
import Package.VIPCustomer;
public class App {
    public static void main(String[] args) throws Exception {
        OfflineStudent offS = new OfflineStudent();
        OnlineStudent onS = new OnlineStudent();
        FullTimeEmployee ftEmp = new FullTimeEmployee();
        PartTimeEmployee ptEmp = new PartTimeEmployee();
        Customer ctm = new Customer();
        VIPCustomer vipCtm = new VIPCustomer();
        Tiger tiger = new Tiger();
        TaxiCar taxi = new TaxiCar();
        System.out.println("-----OfflineStudent-----");
        offS.addName();
        offS.addStudentID();   
        offS.addAge();
        offS.addVehicles();
        offS.displayName();
        offS.displayAge();
        offS.displayStudentID();
        offS.displayVehicles();
        offS.placeToStudy();
        System.out.println("-----OnlineStudent-----");
        onS.addName();
        onS.addStudentID();   
        onS.addAge();
        onS.addDevices();
        onS.displayName();
        onS.displayAge();
        onS.displayStudentID();
        onS.displayDevices();
        onS.placeToStudy();
        System.out.println("-----FullTimeEmployee-----");
        ftEmp.addName();
        ftEmp.addPosition();
        ftEmp.addAge();
        ftEmp.displayName();
        ftEmp.displayAge();
        ftEmp.displayPosition();
        System.out.println("Salary: " + ftEmp.Salary());
        ftEmp.typeOfEmployee();
        System.out.println("-----PartTimeEmployee-----");
        ptEmp.addName();
        ptEmp.addPosition();
        ptEmp.addAge();
        ptEmp.displayName();
        ptEmp.displayAge();
        ptEmp.displayPosition();
        System.out.println("Salary: " + ptEmp.Salary());
        ptEmp.typeOfEmployee();
        System.out.println("-----Customer-----");
        ctm.addName();
        ctm.addCustomerID();
        ctm.addAge();
        ctm.displayName();
        ctm.displayAge();
        ctm.displayCustomerID();
        System.out.println("-----VIPCustomer-----");
        vipCtm.addName();
        vipCtm.addCustomerID();
        vipCtm.addAge();
        vipCtm.displayName();
        vipCtm.displayAge();
        vipCtm.displayCustomerID();
        vipCtm.Gifts();
        System.out.println("-----Animal-----");
        tiger.Eat();
        System.out.println("-----Car-----");
        taxi.Move();
    }
}